# Generated by Django 3.2.4 on 2022-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='florist_address',
            field=models.CharField(default=2, max_length=250, verbose_name='Адрес флориста'),
            preserve_default=False,
        ),
    ]
