# Generated by Django 3.2.4 on 2022-04-15 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, upload_to='Media', verbose_name='Фото')),
                ('instagram', models.URLField(max_length=300, verbose_name='Инстаграм')),
                ('facebook', models.URLField(max_length=300, verbose_name='Фейсбук')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('picture', models.ImageField(blank=True, upload_to='media', verbose_name='Фото')),
                ('open_from', models.TimeField(default=django.utils.timezone.now, verbose_name='Открыто с')),
                ('closed_from', models.TimeField(default=django.utils.timezone.now, verbose_name='Закрыто с')),
            ],
        ),
    ]
