# Generated by Django 3.2.4 on 2022-04-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='instagram',
        ),
    ]
