# Generated by Django 3.2.4 on 2022-04-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('client_status', models.CharField(choices=[('Готовим ваш заказ', 'Preparing'), ('Ваш заказ в пути', 'Ready'), ('Заказ доставлен', 'Delivered')], max_length=255, verbose_name='Статусы клиента')),
                ('courier_status', models.CharField(blank=True, choices=[('Заказ принят', 'Accepted'), ('Еду за заказом', 'Pick Up'), ('Забрал заказ', 'Picked Up'), ('Доставляю', 'Delivering'), ('Заказ доставлен', 'Delivered'), ('Отменить заказ', 'Cancel')], max_length=255, verbose_name='Статусы курьера')),
                ('total_price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('confirm', models.CharField(blank=True, choices=[('Подтвердить заказ', 'Confirm')], max_length=255, verbose_name='Подтвердить заказ')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order')),
            ],
        ),
    ]
