# Generated by Django 3.2.4 on 2022-04-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, upload_to='Media', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='PlantCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, upload_to='Media', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('choice', models.CharField(choices=[('Удобрения', 'Удобрения'), ('Средства защиты', 'Средства защиты'), ('Грунт', 'Грунт'), ('Почва', 'Почва')], max_length=20, verbose_name='Выбор')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, upload_to='Media', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('watering', models.CharField(max_length=255, verbose_name='Полив')),
                ('temperature', models.CharField(max_length=255, verbose_name='Температура')),
                ('sun', models.CharField(max_length=255, verbose_name='Освещение')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Общий объем продаж')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продано')),
                ('is_easy', models.BooleanField(default=False, verbose_name='Легко ухаживать')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
